### ISSUE TITLE
Update Ethereum / RLP Dependencies

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/cert-issuer#110]
We first had to demote RLP to <1 since there was problems with the latest version of pyethereum. 

However, pyethereum was updated and required a newer version of RLP to be compatible. I haven't had time to play around with which combination of dependencies work, but if we could investigate that and get the most up to date of both working again, that would be great. Currently we forced ethereum and RLP to be a specific version that we know works (issue #107).

Essentially, update dependencies, verify ethereum ropsten/mainnet certs still issue without exception. If not, then play around with combinations or leave as is until they are both cooperative again.

**Comment by arycloud** [comment]
Here's what I have in my `etheruem_requirements.txt`:
```
coincurve==7.1.0
rlp<1
ethereum==2.3.1
```
but I'm still getting the same error:
```
Traceback (most recent call last):
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==2.0.22', 'console_scripts', 'cert-issuer')()
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/issue_certificates.py", line 36, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/issue_certificates.py", line 22, in issue
    tx_id = issuer.issue(app_config.chain)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/issuer.py", line 27, in issue
    txid = self.transaction_handler.issue_transaction(blockchain_bytes)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/blockchain_handlers/ethereum/transaction_handlers.py", line 61, in issue_transaction
    self.verify_transaction(signed_tx, eth_data_field)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/blockchain_handlers/ethereum/transaction_handlers.py", line 92, in verify_transaction
    tx_utils.verify_eth_transaction(signed_tx, eth_data_field)
  File "/Users/abdul/PycharmProjects/cert-issuer/venv/lib/python3.5/site-packages/cert_issuer-2.0.22-py3.5.egg/cert_issuer/blockchain_handlers/ethereum/tx_utils.py", line 24, in verify_eth_transaction
    for s in signed_hextx.split('80a0'):
AttributeError: 'dict' object has no attribute 'split'
```
