### ISSUE TITLE
cert-issuer -c /etc/cert-issuer/conf.ini  error

### ISSUE THREAD

**Issue by raymondfx** [blockchain-certificates/cert-issuer#139]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('jsonschema<3.0.0,>=2.5.1'), {'connexion'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cert-issuer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('jsonschema<3.0.0,>=2.5.1'), {'connexion'})

**Comment by Esaie88** [comment]
cert-issuer -c /etc/cert-issuer/conf.ini 
WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the bitcoin_regtest chain
Traceback (most recent call last):
  File "/usr/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==2.0.17', 'console_scripts', 'cert-issuer')()
  File "/usr/lib/python3.6/site-packages/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/usr/lib/python3.6/site-packages/cert_issuer/issue_certificates.py", line 34, in main
    from cert_issuer.blockchain_handlers import bitcoin
  File "/usr/lib/python3.6/site-packages/cert_issuer/blockchain_handlers/bitcoin/__init__.py", line 7, in <module>
    from cert_issuer.blockchain_handlers.bitcoin.connectors import BitcoinServiceProviderConnector, MockServiceProviderConnector
  File "/usr/lib/python3.6/site-packages/cert_issuer/blockchain_handlers/bitcoin/connectors.py", line 13, in <module>
    from pycoin.serialize import b2h, b2h_rev, h2b
ImportError: cannot import name 'b2h'

**Comment by AnthonyRonning** [comment]
@raymondfx I haven't ran into that error before, I know it's been awhile since this ticket was opened - apologies. Do you still have this issue? Make sure you're also in a virtual env. 

@Esaie88 this is a seperate issue that was fixed with https://github.com/blockchain-certificates/cert-issuer/pull/144
