### ISSUE TITLE
issue to the ethereum blockchain coincurve err

### ISSUE THREAD

**Issue by chidoman321** [blockchain-certificates/cert-issuer#198]
Building wheels for collected packages: coincurve
  Building wheel for coincurve (setup.py) ... error

and

Installing collected packages: coincurve
    Running setup.py install for coincurve ... error

could someone push a working branch with ethereum blockchain please ?

```
Building wheels for collected packages: coincurve
  Building wheel for coincurve (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ab9e552w
       cwd: /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/
  Complete output (193 lines):
  Warning: 'keywords' should be a list, got type 'tuple'
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/tests
  copying tests/test_ecdsa.py -> build/lib.linux-x86_64-3.9/tests
  copying tests/test_utils.py -> build/lib.linux-x86_64-3.9/tests
  copying tests/samples.py -> build/lib.linux-x86_64-3.9/tests
  copying tests/test_keys.py -> build/lib.linux-x86_64-3.9/tests
  copying tests/__init__.py -> build/lib.linux-x86_64-3.9/tests
  creating build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/utils.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/flags.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/context.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/keys.py -> build/lib.linux-x86_64-3.9/coincurve
  copying coincurve/__init__.py -> build/lib.linux-x86_64-3.9/coincurve
  running build_clib
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
  checking for gawk... no
  checking for mawk... mawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  checking how to print strings... printf
  checking for style of include used by make... GNU
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking dependency style of gcc... none
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... yes
  checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... no
  checking whether to build static libraries... yes
  checking whether make supports nested variables... (cached) yes
  checking for pkg-config... no
  checking for ar... /usr/bin/ar
  checking for ranlib... /usr/bin/ranlib
  checking for strip... /usr/bin/strip
  checking for gcc... gcc
  checking whether we are using the GNU C compiler... (cached) yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... (cached) none needed
  checking whether gcc understands -c and -o together... (cached) yes
  checking dependency style of gcc... (cached) none
  checking how to run the C preprocessor... gcc -E
  checking for gcc option to accept ISO C89... (cached) none needed
  checking dependency style of gcc... none
  checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
  checking if gcc supports -fvisibility=hidden... yes
  checking for __int128... yes
  checking for __builtin_expect... yes
  checking native compiler: gcc... ok
  checking for x86_64 assembly availability... yes
  checking gmp.h usability... yes
  checking gmp.h presence... yes
  checking for gmp.h... yes
  checking for __gmpz_init in -lgmp... yes
  checking for CRYPTO... no
  checking openssl/crypto.h usability... yes
  checking openssl/crypto.h presence... yes
  checking for openssl/crypto.h... yes
  checking for main in -lcrypto... yes
  checking for EC functions in libcrypto... no
  checking whether byte ordering is bigendian... no
  configure: Using static precomputation: yes
  configure: Using assembly optimizations: x86_64
  configure: Using field implementation: 64bit
  configure: Using bignum implementation: gmp
  configure: Using scalar implementation: 64bit
  configure: Using endomorphism optimizations: no
  configure: Building benchmarks: no
  configure: Building for coverage analysis: no
  configure: Building ECDH module: yes
  configure: Building ECDSA pubkey recovery module: yes
  configure: Using jni: no
  configure: ******
  configure: WARNING: experimental build
  configure: Experimental features do not have stable APIs or properties, and may not be safe for production use.
  configure: Building ECDH module: yes
  configure: ******
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating libsecp256k1.pc
  config.status: creating src/libsecp256k1-config.h
  config.status: executing depfiles commands
  config.status: executing libtool commands
  gcc -I/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1 -g -O2 -Wall -Wextra -Wno-unused-function -c /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/src/gen_context.c -o gen_context.o
  gcc gen_context.o -o gen_context
  ./gen_context
    CC       src/libsecp256k1_la-secp256k1.lo
    CCLD     libsecp256k1.la
  /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
    CC       src/tests-tests.o
    CCLD     tests
    CC       src/exhaustive_tests-tests_exhaustive.o
    CCLD     exhaustive_tests
  make[1]: Entering directory '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9'
   /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib'
   /bin/bash ./libtool   --mode=install /usr/bin/install -c   libsecp256k1.la '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib'
  libtool: install: /usr/bin/install -c .libs/libsecp256k1.lai /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.la
  libtool: install: /usr/bin/install -c .libs/libsecp256k1.a /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
  libtool: install: chmod 644 /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
  libtool: install: /usr/bin/ranlib /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
  libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/sbin" ldconfig -n /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib
  ----------------------------------------------------------------------
  Libraries have been installed in:
     /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib
  
  If you ever happen to want to link against installed libraries
  in a given directory, LIBDIR, you must either use libtool, and
  specify the full pathname of the library, or use the `-LLIBDIR'
  flag during linking and do at least one of the following:
     - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
       during execution
     - add LIBDIR to the `LD_RUN_PATH' environment variable
       during linking
     - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
     - have your system administrator add LIBDIR to `/etc/ld.so.conf'
  
  See any operating system documentation about shared libraries for
  more information, such as the ld(1) and ld.so(8) manual pages.
  ----------------------------------------------------------------------
   /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/include'
   /usr/bin/install -c -m 644 /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1.h /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1_ecdh.h /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1_recovery.h '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/include'
   /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/pkgconfig'
   /usr/bin/install -c -m 644 libsecp256k1.pc '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/pkgconfig'
  make[1]: Leaving directory '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9'
  error: [Errno 2] No such file or directory: 'pkg-config'
  ----------------------------------------
  ERROR: Failed building wheel for coincurve
  Running setup.py clean for coincurve
Failed to build coincurve
Installing collected packages: coincurve
    Running setup.py install for coincurve ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h92ow1ht/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/coincurve
         cwd: /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/
    Complete output (192 lines):
    Warning: 'keywords' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/tests
    copying tests/test_ecdsa.py -> build/lib.linux-x86_64-3.9/tests
    copying tests/test_utils.py -> build/lib.linux-x86_64-3.9/tests
    copying tests/samples.py -> build/lib.linux-x86_64-3.9/tests
    copying tests/test_keys.py -> build/lib.linux-x86_64-3.9/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-3.9/tests
    creating build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/utils.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/ecdsa.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/flags.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/context.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/keys.py -> build/lib.linux-x86_64-3.9/coincurve
    copying coincurve/__init__.py -> build/lib.linux-x86_64-3.9/coincurve
    running build_clib
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... none
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... no
    checking whether to build static libraries... yes
    checking whether make supports nested variables... (cached) yes
    checking for pkg-config... no
    checking for ar... /usr/bin/ar
    checking for ranlib... /usr/bin/ranlib
    checking for strip... /usr/bin/strip
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) none
    checking how to run the C preprocessor... gcc -E
    checking for gcc option to accept ISO C89... (cached) none needed
    checking dependency style of gcc... none
    checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
    checking if gcc supports -fvisibility=hidden... yes
    checking for __int128... yes
    checking for __builtin_expect... yes
    checking native compiler: gcc... ok
    checking for x86_64 assembly availability... yes
    checking gmp.h usability... yes
    checking gmp.h presence... yes
    checking for gmp.h... yes
    checking for __gmpz_init in -lgmp... yes
    checking for CRYPTO... no
    checking openssl/crypto.h usability... yes
    checking openssl/crypto.h presence... yes
    checking for openssl/crypto.h... yes
    checking for main in -lcrypto... yes
    checking for EC functions in libcrypto... no
    checking whether byte ordering is bigendian... no
    configure: Using static precomputation: yes
    configure: Using assembly optimizations: x86_64
    configure: Using field implementation: 64bit
    configure: Using bignum implementation: gmp
    configure: Using scalar implementation: 64bit
    configure: Using endomorphism optimizations: no
    configure: Building benchmarks: no
    configure: Building for coverage analysis: no
    configure: Building ECDH module: yes
    configure: Building ECDSA pubkey recovery module: yes
    configure: Using jni: no
    configure: ******
    configure: WARNING: experimental build
    configure: Experimental features do not have stable APIs or properties, and may not be safe for production use.
    configure: Building ECDH module: yes
    configure: ******
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating libsecp256k1.pc
    config.status: creating src/libsecp256k1-config.h
    config.status: executing depfiles commands
    config.status: executing libtool commands
    gcc -I/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1 -g -O2 -Wall -Wextra -Wno-unused-function -c /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/src/gen_context.c -o gen_context.o
    gcc gen_context.o -o gen_context
    ./gen_context
      CC       src/libsecp256k1_la-secp256k1.lo
      CCLD     libsecp256k1.la
    /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
      CC       src/tests-tests.o
      CCLD     tests
      CC       src/exhaustive_tests-tests_exhaustive.o
      CCLD     exhaustive_tests
    make[1]: Entering directory '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9'
     /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib'
     /bin/bash ./libtool   --mode=install /usr/bin/install -c   libsecp256k1.la '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib'
    libtool: install: /usr/bin/install -c .libs/libsecp256k1.lai /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.la
    libtool: install: /usr/bin/install -c .libs/libsecp256k1.a /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
    libtool: install: chmod 644 /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
    libtool: install: /usr/bin/ranlib /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/libsecp256k1.a
    libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/sbin" ldconfig -n /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib
    ----------------------------------------------------------------------
    Libraries have been installed in:
       /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib
    
    If you ever happen to want to link against installed libraries
    in a given directory, LIBDIR, you must either use libtool, and
    specify the full pathname of the library, or use the `-LLIBDIR'
    flag during linking and do at least one of the following:
       - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
         during execution
       - add LIBDIR to the `LD_RUN_PATH' environment variable
         during linking
       - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
       - have your system administrator add LIBDIR to `/etc/ld.so.conf'
    
    See any operating system documentation about shared libraries for
    more information, such as the ld(1) and ld.so(8) manual pages.
    ----------------------------------------------------------------------
     /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/include'
     /usr/bin/install -c -m 644 /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1.h /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1_ecdh.h /tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/libsecp256k1/include/secp256k1_recovery.h '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/include'
     /usr/bin/mkdir -p '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/pkgconfig'
     /usr/bin/install -c -m 644 libsecp256k1.pc '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9/lib/pkgconfig'
    make[1]: Leaving directory '/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/build/temp.linux-x86_64-3.9'
    error: [Errno 2] No such file or directory: 'pkg-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l25mh98_/coincurve_57696af4e59c4d29b645738fcab84ef8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h92ow1ht/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/coincurve Check the logs for full command output.
Traceback (most recent call last):
  File "/home/chidoman/cert-issuer/setup.py", line 51, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chidoman/cert-issuer/setup.py", line 44, in run
    install(reqs)
  File "/home/chidoman/cert-issuer/setup.py", line 48, in install
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'coincurve==7.1.0\n']' returned non-zero exit status 1.
┌──(root💀)-[/home/chidoman/cert-issuer]
└─# 
```

**Comment by chidoman321** [comment]
i tested master , v3 , v2 branches and all gave a related err 

i dont post this err on the forum because im not able yet

i am using wsl2 if there is any issue related with , please let me know

**Comment by lemoustachiste** [comment]
I encountered an issue today with Mac OS and the absence of the gmp library, which I fixed with 
```
brew install gmp
```

Now your error is different and your environment seems to be linux:
```
error: [Errno 2] No such file or directory: 'pkg-config'
```

To me, this is not an error with cert-issuer but your local configuration. I suggest you research the above error.
