### ISSUE TITLE
cert_issuer.errors.InsufficientFundsError: Please add 500000000000000 wei

### ISSUE THREAD

**Issue by h20190902** [blockchain-certificates/cert-issuer#205]
For the below command I'm facing the issue

python3 /cert-issuer/cert_issuer -c /cert-issuer/conf.ini

```
WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the ethereum_ropsten chain
INFO - Set cost constants to recommended_gas_price=20000000000.000000, recommended_gas_limit=25000.000000
INFO - Processing 1 certificates
INFO - Processing 1 certificates under work path=/cert-issuer/data/work/
INFO - Getting balance with EthereumRPCProvider
WARNING - HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06ddbf8198>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Attention Required! | Cloudflare</title>

<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


  

<style type="text/css">
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
      
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> ropsten.etherscan.io</h2>
      
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form interactive-form" id="challenge-form" action="/api?module=account&amp;action=balance&amp;address=0x4d6919d34132C6963cfEe665309C6079822795BB&amp;tag=pending&amp;__cf_chl_captcha_tk__=77aa2232cc2d8086314bd81dabac4bea8839011a-1624203166-0-Adcgp8T3L_hFqKedTBSh18hEaB5Z40bCSYdzCvF0nH45T1UKVMsYVvReZzRZtWm4D2nuhlJvZS7tQNbStUsbN_xnpjqdrViHxCQfX6f0koqXNkSaWkO5cxnyVR7LwrHdtWI9TEYXzVoWUzliaIeZNEzWR1lmBFXUBKcsC0tv5lNvZwHeb6mGadCykNNHs8VQf_35-pY6JwKrjAihx0wYQgyC3fIG3JvdpkOEKY09P2QBvCxUsPRGokg_YLVGfVwK8_3qmPJgKbA_XNQMT5FZTVyvOVqvLzIRUcJhKCIB1VUHi4Oc3BFl3RdXwT-LudTOlu4Jco2ALj9M3CMeP1xJHbVpIK_U5j44-KpnnmQc3hp4OFz69_w9x9GNMFS6JANmrz4kO7c_KizRma2D4t8EqNKm2Kw3cXQVF7sUuaLZhdldZExEWqBPU7wSOWkiN_le59ibI3he38p320nxL6v4IGG-yapqYCVay-7HUDuJLUoPXHNpjqoihCp18nkzBs7C3WXHN34bTAMC81uWtaXNCFihkg3Nld6jXb0IohVz2ImtQnDO_W4papF6EndOBgK0emZQ_FNaKRpTnd6qbN14BNwbKcEVcs9PkR3X9R89sCoVDrY2O370gAM0EOoqKkCSxjJnfqOIhDDWHXuEacOWCiYqpranzL_BTvpqVCiUDmRHRmYeitSuDV9399g9KH5-U7FRZZonmFY475V_KlI_gjHk5E6Z9jdFzk-h5i5e-_aZMVsJeZEwAOUAVwuWxAea9kNFIVCKhPZlbs8KwXFxiTM" method="POST" enctype="application/x-www-form-urlencoded">
  
  <input type="hidden" name="r" value="0b8eebf875c8e67782a114d797c0b5cdc8f55980-1624203166-0-AWkMEYmKaV7MlOSOY4KAUFkiSJqpZl8hcImfxqtaeUR+riCiPBe266GrnwsF0PNQkE6I7yvaamEKHbUBRXW/a/lHSPSJpF/A/uomHhcXeYh2h9dPxJKU5dAhLq2PEOtqDKpl2gSiXQp6URKKutUYxE+skIuyeRm782tOWDpSmiQyhxiik83qmr/21zHxkWl6DwSBIGCcCJLYksuRZyB8Y38tdKWSkJ1wkKXLF6/JY0VmZwJNiiO9+FRErlyLL0ImVY3b66/XfWbpUyiJgPekkX9NUSnGtRP17Wc3j3zqhSfMXXB5rzrbqBQ2FEtX1e87nHyH6wR72NlSkzbjc8RFJSCnO3W/yaXriWQgjiU3dRLIWKF+V2+4gTt/7PGAywEEVgFP5b4J7ypIecgj4Xw/i/LHnYXye+wJyeXLxt55HZAomeUmLrRz7o5AsIFUndb0SeNUXyHogCP38QRdclVbfyf0Rmhr32Fzso0qNY+B68ubtBUwJ3NzmElSMRq30nwHNbAPa+FsqaXXJ5LqbA9KSZZOEsbHSb7w+vS4d7maRgQGcMYaDOUqDNGeUe37waM8Rs89fCEd6aOIHqjQm9r8ESbEW7mV/dgs6H+X+w0GcD73hn3doXRyk6eO0tllNBYC01kLKaVs8FqpYiPMsA9WEh7PD9TpgzZrc68zYpMaafWbyQiL3UdqadCWIgACnLXQLxFgX0LrkyebzFLx3EFIsf/hfK/kFxQbbrxB1FJUMshAwCdED626VemYPUerAdevzjMHis95wDnfS7TGq1jzDXl0ha/I8t9A/90sdRUnpDajBoBygG3LaxAPxZyJD8N4lAoUFwK8zY7OH+j5voSx2bZp6pKJExCY/ip9k9CwIR5yHD7B2NYUqrvpbNc6iMiUMjrlDRNIknBo0qj5epQFgtdfXpZLGbCv3VYR3voKod/FOmEZ39+X9pOrLhK0BPPAfSXYmL9Vo+tXfkg8MYCkiZcLGQ0gLptSELpPgnVANLXRQCx4O+J0pwFHtqdYp3dDUuBzOh4o1VOcbL7Vd1dRe8UDvnhgf2dhW/OGr2O5kAMLI63miT8aZcguoXAzynJZRbj/TuCFKtK3HgiGcP6zNjfnb126i50fdL3amjdAPsLG3kbFA94Tz/cn+RmVcbUa0FUphfT9UEh0giaKLvT7LnZCQy7XXn2FbeXET9remsyay0g9bvKOCdVqzytFowiD6ZaTikNzhb7MyL79NpbbOjstCY229Eck5Uux0QrEyPfn">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <input type="hidden" name="vc" value="">
  
  <script type="text/javascript" src="/cdn-cgi/scripts/hcaptcha.challenge.js" data-type="normal" data-ray="66260d40a8d7ddaf" async data-sitekey="03196e24-ce02-40fc-aa86-4d6130e1c97a"></script>
  
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script type="text/javascript">
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=66260d40a8d7ddaf')"></div>
</form>
  


              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">66260d40a8d7ddaf</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 20.203.20.108</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>


</body>
</html>

INFO - Total cost will be 500000000000000 wei
ERROR - Please add 500000000000000 wei to the address 0x4d6919d34132C6963cfEe665309C6079822795BB
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cert-issuer/cert_issuer/__main__.py", line 21, in <module>
    cert_issuer_main()
  File "/cert-issuer/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/usr/lib/python3.6/site-packages/cert_issuer/issue_certificates.py", line 36, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/usr/lib/python3.6/site-packages/cert_issuer/issue_certificates.py", line 16, in issue
    transaction_handler.ensure_balance()
  File "/usr/lib/python3.6/site-packages/cert_issuer/blockchain_handlers/ethereum/transaction_handlers.py", line 55, in ensure_balance
    raise InsufficientFundsError(error_message)
cert_issuer.errors.InsufficientFundsError: Please add 500000000000000 wei to the address 0x4d6919d34132C6963cfEe665309C6079822795BB
```

I do have 4 ethr in my test network
<img width="919" alt="Screenshot 2021-06-20 at 9 19 26 PM" src="https://user-images.githubusercontent.com/81671057/122680546-535ddc00-d20d-11eb-9dd2-cc6d81b410ab.png">

**Comment by lemoustachiste** [comment]
I am not too certain of the deeper issue there, but to put you on the right tracks, I think the error comes from the connection error with the RPC:

```
INFO - Getting balance with EthereumRPCProvider
WARNING - HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06ddbf8198>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I haven't spent a lot of time in this project so I don't know all the internals on top of my head, but you might want to look at which ethereum RPC is being called and if you need to provide an account for it. What really catches my attention is this: `Max retries exceeded with url: /`. I don't remember if you need to configure it manually.

**Comment by h20190902** [comment]
Hey @lemoustachiste ,

Thanks for you reply,

But I'm pretty sure the below warning is not an issue.

`INFO - Getting balance with EthereumRPCProvider
WARNING - HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06ddbf8198>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by lemoustachiste** [comment]
Please take a look at #206.
Also you may configure your own RPC provider: https://github.com/blockchain-certificates/cert-issuer/blob/b7d252068e565d1323b283cb9d03a202b3b6e64d/cert_issuer/blockchain_handlers/ethereum/connectors.py#L57

**Comment by sreenumalae** [comment]
If anyone else is facing the same issue
Clone the old commit  commit sha_id c3c723346465d2fb396375217db6cf861808555e

@lemoustachiste this resolves my issue

**Comment by lemoustachiste** [comment]
I am now also facing this issue, I have opened a ticket with Etherscan to understand why the API sends back a captcha challenge.
At this time I recommend using another rpc provider to issue with Ethereum

**Comment by lemoustachiste** [comment]
Ok the fix is to provide `headers` with the request. I have a local fix in the v3 branch, I'll see if I can put it in master too.
