### ISSUE TITLE
Ethereum testnet issuing mode fails

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/cert-issuer#72]
There is no connector configured for Ethereum testnet issuing mode. What is the correct behavior?

This errror was reported:
```
Traceback (most recent call last):
  File "/home/ludo/.local/bin/cert-issuer", line 11, in <module>
    sys.exit(cert_issuer_main())
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/issue_certificates.py", line 68, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/issue_certificates.py", line 35, in issue
    transaction_handler.ensure_balance()
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/transaction_handler.py", line 167, in ensure_balance
    self.balance = self.connector.get_balance(self.issuing_address)
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/connectors.py", line 205, in get_balance
    for m in get_providers_for_chain(self.ethereum_chain, self.local_node):
  File "/home/ludo/.local/lib/python3.5/site-packages/cert_issuer/connectors.py", line 374, in get_providers_for_chain
    return connectors[chain]
KeyError: <Chain.ethereum_testnet: 6>
```

**Comment by AnthonyRonning** [comment]
I'm wondering if we should just remove `ethereum_testnet` as an option, since ethereum has many testnets and none simply referred to as testnet. Right now, Ropsten seems to work well enough with lots of support.

https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids/17101#17101


0: Olympic, Ethereum public pre-release testnet
1: Frontier, Homestead, Metropolis, the Ethereum public main network
1: Classic, the (un)forked public Ethereum Classic main network, chain ID 61
1: Expanse, an alternative Ethereum implementation, chain ID 2
2: Morden, the public Ethereum testnet, now Ethereum Classic testnet
3: Ropsten, the public cross-client Ethereum testnet
4: Rinkeby, the public Geth PoA testnet
8: Ubiq, the public Gubiq main network with flux difficulty chain ID 8
42: Kovan, the public Parity PoA testnet
77: Sokol, the public POA Network testnet
99: Core, the public POA Network main network
7762959: Musicoin, the music blockchain
[Other]: Could indicate that your connected to a local development test network.

**Comment by AnthonyRonning** [comment]
Removed.
